export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PHOTO_UPDATE = "PHOTO_UPDATE";
export const SUMMARY_UPDATE = "SUMMARY_UPDATE";
export const SKILLS_UPDATE = "SKILLS_UPDATE";
export const EXPERIENCE_UPDATE = "EXPERIENCE_UPDATE";
export const EDUCATION_UPDATE = "EDUCATION_UPDATE";
export const PRIVATE_UPDATE = "PRIVATE_UPDATE";